--------------------------------------------------------
-- Archivo creado  - domingo-septiembre-19-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIENTES
--------------------------------------------------------

  CREATE TABLE "USER12"."CLIENTES" 
   (	"DNI" CHAR(8 BYTE), 
	"NOMBRES" VARCHAR2(30 BYTE), 
	"AP_PATERNO" VARCHAR2(30 BYTE), 
	"AP_MATERNO" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"TELEFONO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GRUPO12" ;
--------------------------------------------------------
--  DDL for Table CUENTAS
--------------------------------------------------------

  CREATE TABLE "USER12"."CUENTAS" 
   (	"NUMERO_CTA" CHAR(5 BYTE), 
	"NIP" CHAR(5 BYTE), 
	"MONEDA" VARCHAR2(20 BYTE), 
	"SALDO" NUMBER(*,0), 
	"DNI_CLIENTE" CHAR(8 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GRUPO12" ;
--------------------------------------------------------
--  DDL for Table MOVIMIENTOS
--------------------------------------------------------

  CREATE TABLE "USER12"."MOVIMIENTOS" 
   (	"NUMERO_OP" NUMBER(*,0), 
	"FECHA_HORA" TIMESTAMP (6), 
	"TIPO" NUMBER(*,0), 
	"IMPORTE" NUMBER(*,0), 
	"NUMERO_CTA" CHAR(5 BYTE), 
	"CODIGO_CAJERO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GRUPO12" ;
--------------------------------------------------------
--  DDL for Table TIPOS_TRANSACCION
--------------------------------------------------------

  CREATE TABLE "USER12"."TIPOS_TRANSACCION" 
   (	"CODIGO" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GRUPO12" ;
REM INSERTING into USER12.CLIENTES
SET DEFINE OFF;
REM INSERTING into USER12.CUENTAS
SET DEFINE OFF;
REM INSERTING into USER12.MOVIMIENTOS
SET DEFINE OFF;
REM INSERTING into USER12.TIPOS_TRANSACCION
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index CLIENTES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER12"."CLIENTES_PK" ON "USER12"."CLIENTES" ("DNI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GRUPO12" ;
--------------------------------------------------------
--  DDL for Index CUENTAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER12"."CUENTAS_PK" ON "USER12"."CUENTAS" ("NUMERO_CTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GRUPO12" ;
--------------------------------------------------------
--  DDL for Index MOVIMIENTOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER12"."MOVIMIENTOS_PK" ON "USER12"."MOVIMIENTOS" ("NUMERO_OP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GRUPO12" ;
--------------------------------------------------------
--  DDL for Index TIPOS_TRANSACCION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER12"."TIPOS_TRANSACCION_PK" ON "USER12"."TIPOS_TRANSACCION" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GRUPO12" ;
--------------------------------------------------------
--  Constraints for Table MOVIMIENTOS
--------------------------------------------------------

  ALTER TABLE "USER12"."MOVIMIENTOS" ADD CONSTRAINT "MOVIMIENTOS_PK" PRIMARY KEY ("NUMERO_OP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GRUPO12"  ENABLE;
  ALTER TABLE "USER12"."MOVIMIENTOS" MODIFY ("CODIGO_CAJERO" NOT NULL ENABLE);
  ALTER TABLE "USER12"."MOVIMIENTOS" MODIFY ("NUMERO_CTA" NOT NULL ENABLE);
  ALTER TABLE "USER12"."MOVIMIENTOS" MODIFY ("IMPORTE" NOT NULL ENABLE);
  ALTER TABLE "USER12"."MOVIMIENTOS" MODIFY ("TIPO" NOT NULL ENABLE);
  ALTER TABLE "USER12"."MOVIMIENTOS" MODIFY ("FECHA_HORA" NOT NULL ENABLE);
  ALTER TABLE "USER12"."MOVIMIENTOS" MODIFY ("NUMERO_OP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENTES
--------------------------------------------------------

  ALTER TABLE "USER12"."CLIENTES" ADD CONSTRAINT "CLIENTES_PK" PRIMARY KEY ("DNI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GRUPO12"  ENABLE;
  ALTER TABLE "USER12"."CLIENTES" MODIFY ("AP_MATERNO" NOT NULL ENABLE);
  ALTER TABLE "USER12"."CLIENTES" MODIFY ("AP_PATERNO" NOT NULL ENABLE);
  ALTER TABLE "USER12"."CLIENTES" MODIFY ("NOMBRES" NOT NULL ENABLE);
  ALTER TABLE "USER12"."CLIENTES" MODIFY ("DNI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CUENTAS
--------------------------------------------------------

  ALTER TABLE "USER12"."CUENTAS" ADD CONSTRAINT "CUENTAS_PK" PRIMARY KEY ("NUMERO_CTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GRUPO12"  ENABLE;
  ALTER TABLE "USER12"."CUENTAS" MODIFY ("DNI_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "USER12"."CUENTAS" MODIFY ("SALDO" NOT NULL ENABLE);
  ALTER TABLE "USER12"."CUENTAS" MODIFY ("MONEDA" NOT NULL ENABLE);
  ALTER TABLE "USER12"."CUENTAS" MODIFY ("NIP" NOT NULL ENABLE);
  ALTER TABLE "USER12"."CUENTAS" MODIFY ("NUMERO_CTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPOS_TRANSACCION
--------------------------------------------------------

  ALTER TABLE "USER12"."TIPOS_TRANSACCION" ADD CONSTRAINT "TIPOS_TRANSACCION_PK" PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GRUPO12"  ENABLE;
  ALTER TABLE "USER12"."TIPOS_TRANSACCION" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "USER12"."TIPOS_TRANSACCION" MODIFY ("CODIGO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CUENTAS
--------------------------------------------------------

  ALTER TABLE "USER12"."CUENTAS" ADD CONSTRAINT "CUENTAS_CLIENTES_FK" FOREIGN KEY ("DNI_CLIENTE")
	  REFERENCES "USER12"."CLIENTES" ("DNI") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MOVIMIENTOS
--------------------------------------------------------

  ALTER TABLE "USER12"."MOVIMIENTOS" ADD CONSTRAINT "MOVIMIENTOS_CUENTAS_FK" FOREIGN KEY ("NUMERO_CTA")
	  REFERENCES "USER12"."CUENTAS" ("NUMERO_CTA") ENABLE;
  ALTER TABLE "USER12"."MOVIMIENTOS" ADD CONSTRAINT "MOVIMIENTOS_TIPOS" FOREIGN KEY ("TIPO")
	  REFERENCES "USER12"."TIPOS_TRANSACCION" ("CODIGO") ENABLE;
